// Autogenerated from Pigeon (v22.7.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Available types for a [Place]
///
/// Ref: https://developers.google.com/maps/documentation/places/android-sdk/supported_types
enum PlaceType {
  OTHER,
  ACCOUNTING,
  ADMINISTRATIVE_AREA_LEVEL_1,
  ADMINISTRATIVE_AREA_LEVEL_2,
  ADMINISTRATIVE_AREA_LEVEL_3,
  ADMINISTRATIVE_AREA_LEVEL_4,
  ADMINISTRATIVE_AREA_LEVEL_5,
  AIRPORT,
  AMUSEMENT_PARK,
  AQUARIUM,
  ARCHIPELAGO,
  ART_GALLERY,
  ATM,
  BAKERY,
  BANK,
  BAR,
  BEAUTY_SALON,
  BICYCLE_STORE,
  BOOK_STORE,
  BOWLING_ALLEY,
  BUS_STATION,
  CAFE,
  CAMPGROUND,
  CAR_DEALER,
  CAR_RENTAL,
  CAR_REPAIR,
  CAR_WASH,
  CASINO,
  CEMETERY,
  CHURCH,
  CITY_HALL,
  CLOTHING_STORE,
  COLLOQUIAL_AREA,
  CONTINENT,
  CONVENIENCE_STORE,
  COUNTRY,
  COURTHOUSE,
  DENTIST,
  DEPARTMENT_STORE,
  DOCTOR,
  DRUGSTORE,
  ELECTRICIAN,
  ELECTRONICS_STORE,
  EMBASSY,
  ESTABLISHMENT,
  FINANCE,
  FIRE_STATION,
  FLOOR,
  FLORIST,
  FOOD,
  FUNERAL_HOME,
  FURNITURE_STORE,
  GAS_STATION,
  GENERAL_CONTRACTOR,
  GEOCODE,
  GROCERY_OR_SUPERMARKET,
  GYM,
  HAIR_CARE,
  HARDWARE_STORE,
  HEALTH,
  HINDU_TEMPLE,
  HOME_GOODS_STORE,
  HOSPITAL,
  INSURANCE_AGENCY,
  INTERSECTION,
  JEWELRY_STORE,
  LAUNDRY,
  LAWYER,
  LIBRARY,
  LIGHT_RAIL_STATION,
  LIQUOR_STORE,
  LOCAL_GOVERNMENT_OFFICE,
  LOCALITY,
  LOCKSMITH,
  LODGING,
  MEAL_DELIVERY,
  MEAL_TAKEAWAY,
  MOSQUE,
  MOVIE_RENTAL,
  MOVIE_THEATER,
  MOVING_COMPANY,
  MUSEUM,
  NATURAL_FEATURE,
  NEIGHBORHOOD,
  NIGHT_CLUB,
  PAINTER,
  PARK,
  PARKING,
  PET_STORE,
  PHARMACY,
  PHYSIOTHERAPIST,
  PLACE_OF_WORSHIP,
  PLUMBER,
  PLUS_CODE,
  POINT_OF_INTEREST,
  POLICE,
  POLITICAL,
  POST_BOX,
  POST_OFFICE,
  POSTAL_CODE_PREFIX,
  POSTAL_CODE_SUFFIX,
  POSTAL_CODE,
  POSTAL_TOWN,
  PREMISE,
  PRIMARY_SCHOOL,
  REAL_ESTATE_AGENCY,
  RESTAURANT,
  ROOFING_CONTRACTOR,
  ROOM,
  ROUTE,
  RV_PARK,
  SCHOOL,
  SECONDARY_SCHOOL,
  SHOE_STORE,
  SHOPPING_MALL,
  SPA,
  STADIUM,
  STORAGE,
  STORE,
  STREET_ADDRESS,
  STREET_NUMBER,
  SUBLOCALITY_LEVEL_1,
  SUBLOCALITY_LEVEL_2,
  SUBLOCALITY_LEVEL_3,
  SUBLOCALITY_LEVEL_4,
  SUBLOCALITY_LEVEL_5,
  SUBLOCALITY,
  SUBPREMISE,
  SUBWAY_STATION,
  SUPERMARKET,
  SYNAGOGUE,
  TAXI_STAND,
  TOURIST_ATTRACTION,
  TOWN_SQUARE,
  TRAIN_STATION,
  TRANSIT_STATION,
  TRAVEL_AGENCY,
  UNIVERSITY,
  VETERINARY_CARE,
  ZOO,
  /// Places (new) types
  AMERICAN_RESTAURANT,
  DISCOUNT_STORE,
  ICE_CREAM_SHOP,
  SANDWICH_SHOP,
  AMUSEMENT_CENTER,
  DOG_PARK,
  INDIAN_RESTAURANT,
  SCHOOL_DISTRICT,
  ATHLETIC_FIELD,
  ELECTRIC_VEHICLE_CHARGING_STATION,
  INDONESIAN_RESTAURANT,
  SEAFOOD_RESTAURANT,
  AUTO_PARTS_STORE,
  EVENT_VENUE,
  ITALIAN_RESTAURANT,
  SKI_RESORT,
  BANQUET_HALL,
  EXTENDED_STAY_HOTEL,
  JAPANESE_RESTAURANT,
  SPANISH_RESTAURANT,
  BARBECUE_RESTAURANT,
  FARM,
  KOREAN_RESTAURANT,
  SPORTING_GOODS_STORE,
  BARBER_SHOP,
  FARMSTAY,
  LEBANESE_RESTAURANT,
  SPORTS_CLUB,
  BED_AND_BREAKFAST,
  FAST_FOOD_RESTAURANT,
  MARINA,
  SPORTS_COMPLEX,
  BRAZILIAN_RESTAURANT,
  FERRY_TERMINAL,
  MARKET,
  STEAK_HOUSE,
  BREAKFAST_RESTAURANT,
  FITNESS_CENTER,
  MEDICAL_LAB,
  SUSHI_RESTAURANT,
  BRUNCH_RESTAURANT,
  FRENCH_RESTAURANT,
  MEDITERRANEAN_RESTAURANT,
  SWIMMING_POOL,
  BUS_STOP,
  GIFT_SHOP,
  MEXICAN_RESTAURANT,
  TAILOR,
  CAMPING_CABIN,
  GOLF_COURSE,
  MIDDLE_EASTERN_RESTAURANT,
  TELECOMMUNICATIONS_SERVICE_PROVIDER,
  CELL_PHONE_STORE,
  GREEK_RESTAURANT,
  MOTEL,
  THAI_RESTAURANT,
  CHILD_CARE_AGENCY,
  GROCERY_STORE,
  NATIONAL_PARK,
  TRANSIT_DEPOT,
  CHINESE_RESTAURANT,
  GUEST_HOUSE,
  PARK_AND_RIDE,
  TRUCK_STOP,
  COFFEE_SHOP,
  HAIR_SALON,
  PERFORMING_ARTS_THEATER,
  TURKISH_RESTAURANT,
  COMMUNITY_CENTER,
  HAMBURGER_RESTAURANT,
  PIZZA_RESTAURANT,
  VEGAN_RESTAURANT,
  CONSULTANT,
  HELIPORT,
  PLAYGROUND,
  VEGETARIAN_RESTAURANT,
  CONVENTION_CENTER,
  HIKING_AREA,
  PRESCHOOL,
  VIETNAMESE_RESTAURANT,
  COTTAGE,
  HISTORICAL_LANDMARK,
  PRIVATE_GUEST_ROOM,
  VISITOR_CENTER,
  COURIER_SERVICE,
  HOME_IMPROVEMENT_STORE,
  RAMEN_RESTAURANT,
  WEDDING_VENUE,
  CULTURAL_CENTER,
  HOSTEL,
  RESORT_HOTEL,
  WHOLESALER,
  DENTAL_CLINIC,
  HOTEL,
  REST_STOP,
}

class PlacesLocale {
  PlacesLocale({
    required this.country,
    required this.language,
  });

  String country;

  String language;

  Object encode() {
    return <Object?>[
      country,
      language,
    ];
  }

  static PlacesLocale decode(Object result) {
    result as List<Object?>;
    return PlacesLocale(
      country: result[0]! as String,
      language: result[1]! as String,
    );
  }
}

class LatLng {
  LatLng({
    required this.lat,
    required this.lng,
  });

  double lat;

  double lng;

  Object encode() {
    return <Object?>[
      lat,
      lng,
    ];
  }

  static LatLng decode(Object result) {
    result as List<Object?>;
    return LatLng(
      lat: result[0]! as double,
      lng: result[1]! as double,
    );
  }
}

class LatLngBounds {
  LatLngBounds({
    required this.southwest,
    required this.northeast,
  });

  /// The southwest coordinate of the bounds.
  LatLng southwest;

  /// The northeast coordinate of the bounds.
  LatLng northeast;

  Object encode() {
    return <Object?>[
      southwest,
      northeast,
    ];
  }

  static LatLngBounds decode(Object result) {
    result as List<Object?>;
    return LatLngBounds(
      southwest: result[0]! as LatLng,
      northeast: result[1]! as LatLng,
    );
  }
}

class AutocompletePrediction {
  AutocompletePrediction({
    this.distanceMeters,
    required this.placeId,
    this.placeTypes,
    required this.primaryText,
    required this.secondaryText,
    required this.fullText,
  });

  /// the straight-line distance between the place being referred to by getPlaceId() and the origin specified in the request.
  int? distanceMeters;

  /// the place ID of the place being referred to by this prediction.
  String placeId;

  /// the list of place types associated with the place referred to by getPlaceId()
  List<PlaceType>? placeTypes;

  /// the primary text of a place.
  String primaryText;

  /// the secondary text of a place.
  String secondaryText;

  /// The full text of a place.
  String fullText;

  Object encode() {
    return <Object?>[
      distanceMeters,
      placeId,
      placeTypes,
      primaryText,
      secondaryText,
      fullText,
    ];
  }

  static AutocompletePrediction decode(Object result) {
    result as List<Object?>;
    return AutocompletePrediction(
      distanceMeters: result[0] as int?,
      placeId: result[1]! as String,
      placeTypes: (result[2] as List<Object?>?)?.cast<PlaceType>(),
      primaryText: result[3]! as String,
      secondaryText: result[4]! as String,
      fullText: result[5]! as String,
    );
  }
}

class FindAutocompletePredictionsResponse {
  FindAutocompletePredictionsResponse({
    required this.predictions,
  });

  List<AutocompletePrediction> predictions;

  Object encode() {
    return <Object?>[
      predictions,
    ];
  }

  static FindAutocompletePredictionsResponse decode(Object result) {
    result as List<Object?>;
    return FindAutocompletePredictionsResponse(
      predictions: (result[0] as List<Object?>?)!.cast<AutocompletePrediction>(),
    );
  }
}

class AddressComponent {
  AddressComponent({
    required this.name,
    required this.shortName,
    required this.types,
  });

  /// Name of the address component, e.g. "Sydney".
  String name;

  /// Short name of the address component, e.g. "AU".
  String shortName;

  /// Types of the AddressComponent
  ///
  /// For a list of supported types, see [Address Component Types](https://developers.google.com/maps/documentation/geocoding/overview#Types)
  List<String> types;

  Object encode() {
    return <Object?>[
      name,
      shortName,
      types,
    ];
  }

  static AddressComponent decode(Object result) {
    result as List<Object?>;
    return AddressComponent(
      name: result[0]! as String,
      shortName: result[1]! as String,
      types: (result[2] as List<Object?>?)!.cast<String>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlaceType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlacesLocale) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LatLng) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is LatLngBounds) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AutocompletePrediction) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is FindAutocompletePredictionsResponse) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is AddressComponent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlaceType.values[value];
      case 130: 
        return PlacesLocale.decode(readValue(buffer)!);
      case 131: 
        return LatLng.decode(readValue(buffer)!);
      case 132: 
        return LatLngBounds.decode(readValue(buffer)!);
      case 133: 
        return AutocompletePrediction.decode(readValue(buffer)!);
      case 134: 
        return FindAutocompletePredictionsResponse.decode(readValue(buffer)!);
      case 135: 
        return AddressComponent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GooglePlacesHostApi {
  /// Constructor for [GooglePlacesHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GooglePlacesHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// This puts Places into its uninitialized state.
  ///
  /// Note: this does not need to be called in order to change the API key
  Future<void> deinitialize() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_google_places_sdk_platform_interface.GooglePlacesHostApi.deinitialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Initializes Places for the given application context with the given API key. Use [useNewApi] to enable the Places API (New) in the SDK
  ///
  /// All Places API responses are localized using the device's locale.
  /// This method should only be called once prior to using the Places API.
  /// You may call this method again to update the API key used;
  /// if so, all widgets and instances of PlacesClient will now use this new key.
  Future<void> initialize(String apiKey, {PlacesLocale? locale, bool? useNewApi, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_google_places_sdk_platform_interface.GooglePlacesHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[apiKey, locale, useNewApi]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns whether or not the internal Places client has been initialized.
  Future<bool?> isInitialized() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_google_places_sdk_platform_interface.GooglePlacesHostApi.isInitialized$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as bool?);
    }
  }

  /// Updates the settings of the places client with the given API key and locale.
  Future<void> updateSettings(String apiKey, {PlacesLocale? locale, bool? useNewApi, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_google_places_sdk_platform_interface.GooglePlacesHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[apiKey, locale, useNewApi]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Fetches autocomplete predictions based on a query.
  ///
  /// If [countries]] is not null, the results are restricted to those countries.
  ///
  /// [AutocompletePrediction.distanceMeters] is calculated from [origin],
  /// if available. If [origin] is null, no distances will be included in the
  /// response.
  ///
  /// When making multiple requests, a session token is saved on one request
  /// and the same is sent to the following ones
  ///
  /// If [newSessionToken] is null, a previously-saved session token will be used.
  /// If there is no previously-saved session token exist, a request without
  /// a session token will be saved and the result token will be saved.
  ///
  /// For more about session tokens: https://developers.google.com/maps/documentation/places/android-sdk/session-tokens
  Future<FindAutocompletePredictionsResponse> findAutocompletePredictions(String query, {List<String>? countries, List<String> placeTypesFilter = const [], bool? newSessionToken, LatLng? origin, LatLngBounds? locationBias, LatLngBounds? locationRestriction, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_google_places_sdk_platform_interface.GooglePlacesHostApi.findAutocompletePredictions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[query, countries, placeTypesFilter, newSessionToken, origin, locationBias, locationRestriction]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as FindAutocompletePredictionsResponse?)!;
    }
  }
}
